server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://iacmjkyetozmyn:fe854eb0925ea751e0c16bf5114d19a4ec3878f80f955793d3534e554b2a549e@ec2-34-206-8-52.compute-1.amazonaws.com:5432/d8b15fv33a56t4
    username: iacmjkyetozmyn
    password: fe854eb0925ea751e0c16bf5114d19a4ec3878f80f955793d3534e554b2a549e
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp Dio - Santander / Backend